CC			:= clang
CFLAGS		:= -Wall -Wextra -Werror -Iinclude -I../lib/include
LD			:= clang
LD_FLAGS		:= -g

RM			:= rm -rf

.DEFAULT_GOAL	:= all 

clean:
	@$(RM) $(OBJS)

fclean: clean
	@$(RM) $(TARGET)

re: fclean all

%.o:%.c
	@$(CC) $(CFLAGS) -c $< -o $@
	@printf "CC\t$<\n"
